name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout this repo (for workflow files)
      uses: actions/checkout@v3

    - name: Install packages
      run: |
        sudo apt update
        sudo apt install -y git device-tree-compiler lz4 xz-utils zlib1g-dev openjdk-17-jdk gcc g++ python3 python-is-python3 p7zip-full android-sdk-libsparse-utils erofs-utils \
        default-jdk git gnupg flex bison gperf build-essential zip curl libc6-dev libncurses-dev libx11-dev libreadline-dev libgl1 libgl1-mesa-dev \
        python3 make sudo gcc g++ bc grep tofrodos python3-markdown libxml2-utils xsltproc zlib1g-dev python-is-python3 libc6-dev libtinfo6 \
        make repo cpio kmod openssl libelf-dev pahole libssl-dev libarchive-tools zstd repo

    - name: Setup repo directory and init
      run: |
        mkdir s5e8845-kernel
        cd s5e8845-kernel
        repo init -u https://github.com/kastentop2005/kernel_manifest.git -b ${{ github.event.inputs.branch }}
        repo sync
      shell: bash

    - name: Build kernel
      run: |
        cd s5e8845-kernel
        ./build.sh
      shell: bash

    - name: Upload boot.img artifact
      uses: actions/upload-artifact@v4
      with:
        name: boot-image
        path: s5e8845-kernel/out/s5e8845_user/dist/boot.img
